# Use Node.js base image
FROM node:20

# Set working directory inside container
WORKDIR /app/frontend

# Copy package.json and package-lock.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app files
COPY . .

# Build the Next.js app
RUN npm run build

# Expose the port Next.js will run on (default is 3000)
EXPOSE 3000

# Command to start the Next.js app (for production)
CMD ["npm", "run", "start"]
