services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    networks:
      - mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword" ]
      interval: 10s
      retries: 5
      start_period: 5s

  backend:
    depends_on:
      db:
        condition: service_healthy
    build: ./yolo
    restart: always
    image: backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: mydatabase
    networks:
      - mysql-network
    volumes:
      - ./yolo:/app/backend
      # - /app/backend/node_modules

      # frontend:
      #   build: ./yolo_front
      #   image: frontend
      #   restart: always
      #   ports:
      #     - "3000:3000"

  nginx:
    image: nginx:latest
    depends_on:
      # - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - mysql-network

networks:
  mysql-network:


volumes:
  mysql_data:
